openzipkin/zipkin-finagle

finagle-zipkin-kafka/src/main/resources/BUILD, finagle-zipkin-kafka/src/main/resources/META-INF/services/com.twitter.finagle.tracing.Tracer, finagle-zipkin-kafka/src/main/scala/BUILD, finagle-zipkin-kafka/src/main/scala/com/twitter/finagle/zipkin/Flags.scala, finagle-zipkin-kafka/src/main/scala/com/twitter/finagle/zipkin/kafka/KafkaRawZipkinTracer.scala, finagle-zipkin-kafka/src/main/scala/com/twitter/finagle/zipkin/kafka/KafkaZipkinTracer.scala, finagle-zipkin-kafka/src/test/scala/BUILD, finagle-zipkin-kafka/src/test/scala/com/twitter/finagle/zipkin/kafka/KafkaRawZipkinTracerTest.scala
See: https://github.com/twitter/finagle/pull/515
=> Zipkin tracer using Kafka as a transport

README.md, http/pom.xml, http/src/main/java/zipkin/finagle/InternalJavaDocDummy.java, http/src/main/resources/META-INF/services/com.twitter.finagle.tracing.Tracer, http/src/main/scala/com/twitter/finagle/zipkin/core/InternalZipkinTracer.scala, http/src/main/scala/zipkin/Flags.scala, http/src/main/scala/zipkin/finagle/http/HttpRawZipkinTracer.scala, http/src/main/scala/zipkin/finagle/http/HttpZipkinTracer.scala, http/src/main/scala/zipkin/http/Flags.scala, http/src/test/scala/zipkin/finagle/http/FlagsTest.scala, http/src/test/scala/zipkin/finagle/http/HttpRawZipkinTracerTest.scala, pom.xml
This is a port of the old tracer that used to be in zipkin-web
=> Adds HttpZipkinTracer

core/src/main/java/zipkin/finagle/MutableSpan.java, core/src/test/java/zipkin/finagle/SpanRecorderTest.java
=> Sets timestamp and duration authoritatively

core/src/main/java/zipkin/finagle/SpanRecorder.java, core/src/main/java/zipkin/finagle/ZipkinTracer.java, core/src/test/java/zipkin/finagle/FakeSender.java, core/src/test/java/zipkin/finagle/SpanRecorderTest.java, http/pom.xml, http/src/main/java/zipkin/finagle/http/HttpSender.java, http/src/main/java/zipkin/finagle/http/HttpZipkinTracer.java, kafka/pom.xml, kafka/src/main/java/zipkin/finagle/kafka/KafkaZipkinTracer.java, kafka/src/test/java/zipkin/finagle/kafka/KafkaZipkinTracerTest.java, pom.xml
This updates code to use the latest zipkin-reporter-java
=> Updates to latest zipkin-reporter and finagle

core/src/main/java/zipkin/finagle/SpanRecorder.java, http/src/test/java/zipkin/finagle/http/HttpZipkinTracerIntegrationTest.java, pom.xml
Remove deprecated c.t.f.tracing.Trace.recordRpcName
=> Updates to finagle 6.45.0

core/pom.xml, core/src/main/java/zipkin/finagle/FinagleSender.java, core/src/main/java/zipkin/finagle/SpanRecorder.java, core/src/test/java/zipkin/finagle/FinagleTestObjects.java, pom.xml, scribe/pom.xml, scribe/src/main/java/zipkin/finagle/scribe/ScribeSender.java
We'll soon start supporting zipkin v2. This begins the decoupling from
v1 internals.
=> Avoids zipkin internal classes and shades where impossible

core/src/main/java/zipkin/finagle/MutableSpan.java, core/src/test/java/zipkin/finagle/ZipkinTracerTest.java, pom.xml
won't work for real until https://github.com/twitter/finagle/pull/651#issuecomment-345627521
=> Supports 128-bit trace ID

pom.xml
=> another month, another version of finagle

pom.xml
to 18.5.0 in lock step with the twitter release cadence.
=> update fingale version

pom.xml
=> Update twitter ecosystem version

core/src/main/java/zipkin2/finagle/SpanRecorder.java, core/src/test/java/zipkin2/finagle/SpanRecorderTest.java, core/src/test/java/zipkin2/finagle/ZipkinTracerIntegrationTest.java, core/src/test/java/zipkin2/finagle/ZipkinTracerTest.java, http/src/test/java/zipkin2/finagle/http/HttpZipkinTracerIntegrationTest.java, kafka/src/test/java/zipkin2/finagle/kafka/KafkaZipkinTracerIntegrationTest.java, pom.xml, scribe/src/test/java/zipkin2/finagle/scribe/ScribeZipkinTracerIntegrationTest.java
=> Finagle update

pom.xml
=> update finagle version

pom.xml
=> Upgrade finagle

pom.xml
with a new release of finagle et. al.
=> welcome in 2019

kafka/src/test/java/zipkin2/finagle/kafka/KafkaZipkinTracerIntegrationTest.java, pom.xml
=> Finagle February 2019

pom.xml
continue our monthly dance with twitter
=> upgrade finagle to 19.9.0

pom.xml
this is the companion to the scala 2.13 upgrade PR #78 but still on 2.12
=> Finagle 20.1.0

pom.xml
to put resource file to set default tracer to zipkin-finagle All this to fix #99
=> alter pom resource config

core/pom.xml, core/src/test/java/zipkin2/finagle/SpanRecorderTest.java, http/pom.xml, kafka/pom.xml, pom.xml, scribe/pom.xml
this is my second try at this. hopefully it does better than the last one
=> update to finagle 22.1.0

pom.xml
I need to build this for various reasons. Once it's in I'll move forward and release 22.7.0
=> Update finagle to 22.4.0

.github/workflows/deploy.yml, pom.xml
=> Fix deploy workflow & few dependency updates 

core/pom.xml, http/pom.xml, kafka/pom.xml, pom.xml, scribe/pom.xml
Set version to -SNAPSHOT, mistakenly it was set to release 23.0.0
=> Set version to -SNAPSHOT

.github/workflows/create_release.yml
=> Fix GA release workflow
